[package]
name = "gb-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.29.9", features = ["rwh_05"] }
assert_no_alloc = "1.1.2"
cpal = "0.15.2"
fundsp = "0.16.0"
clap = { version = "4.4.14", features = ["derive"] }
bitflags = "2.4.1"
log = "0.4.20"
wgpu = "0.18.0"
tokio = { version = "1.35.1", features = ["full"] }
bytemuck = { version = "1.14.0", features = ["derive"] }
num-traits = "0.2"
num-derive = "0.4"